// Curated source material (exported from NotebookLM — notebook "GOODS", 18 sources:
// Đệ Tử Quy, Khổng Tử, Phật pháp / các bậc đế vương + Jean Piaget, Montessori, Secure
// Attachment, Positive Parenting) that the AI Coach should ground its answers in,
// beyond its own general training. Synthesized 2026-07-15 via NotebookLM's own chat
// (all 18 sources selected) into 15 practical, source-attributed principles.
export const GROUNDING_SOURCES = [
  `Sửa mình trước khi sửa con — Trẻ em giống như "miếng bọt biển" hấp thụ toàn bộ năng lượng và môi trường từ cha mẹ (theo Thuyết trí tuệ thấm hút của Montessori). Lời Phật dạy "vạn pháp do tâm tạo" và triết lý "thân giáo" của Khổng Tử chỉ ra rằng, thay vì la mắng ép con thay đổi, cha mẹ phải tự quản lý cảm xúc, giữ chánh niệm và làm gương từ hành vi nhỏ nhất để tạo ra một môi trường an lành cho con.`,
  `Sức mạnh của ái ngữ và tương tác — Lời nói dịu dàng, thấu hiểu (ái ngữ trong Đạo Phật) kết hợp với các cuộc "trò chuyện qua lại" (serve and return) giúp trẻ kích thích vùng não ngôn ngữ và phát triển tư duy phản biện. Giao tiếp bằng câu hỏi mở thay vì mệnh lệnh vừa giúp trẻ cảm thấy an toàn, vừa là yếu tố dự báo thành công tương lai theo nghiên cứu của ĐH Harvard.`,
  `Sự im lặng chữa lành — Khi con bùng nổ cảm xúc (ăn vạ), quát tháo chỉ như đổ thêm dầu vào lửa, khiến hệ thần kinh trẻ phản kháng mạnh hơn. Theo Thuyết gắn bó an toàn (Secure Attachment) và lời Phật dạy, cha mẹ nên lùi lại, ngồi ngang tầm mắt con và dùng "im lặng chánh niệm" làm nơi trú ẩn an toàn, đợi cơn cảm xúc qua đi rồi mới nhẹ nhàng phân tích.`,
  `Khung giờ vàng của tiềm thức — 15 phút trước khi ngủ và ngay sau khi thức dậy là lúc sóng não trẻ thư giãn, ý thức ngừng kháng cự. Đây là "Special Time" (theo Positive Parenting) lý tưởng để cha mẹ thì thầm lời xin lỗi, xoa dịu tổn thương trong ngày và gieo những gợi ý tích cực.`,
  `Tình yêu vô hình và chịu trách nhiệm — Thương con không có nghĩa là bao bọc hay dọn hậu quả thay con (overparenting). Kết hợp "kỷ luật của đế vương" với phong cách nuôi dạy Uy quyền (Authoritative): thiết lập ranh giới rõ ràng, để trẻ đối mặt hậu quả tự nhiên và tự sửa lỗi (như Gia Cát Lượng bắt con tự dán lại cuốn sách rách) để rèn bản lĩnh.`,
  `Giáo dục thuận theo giai đoạn — Cách dạy phải theo sự phát triển não bộ của trẻ (4 giai đoạn nhận thức của Jean Piaget, 6 giai đoạn theo Khổng Tử). Dưới 3 tuổi: dạy bằng hành động làm gương. 3–7 tuổi: dạy qua nguyên tắc và kể chuyện. Trên 11 tuổi: tranh biện bằng lý trí thay vì áp đặt.`,
  `Bảo vệ lòng tự trọng và thể diện — Khổng Tử dạy "người không biết xấu hổ không thể dạy được"; tâm lý học hiện đại cảnh báo nguy cơ của việc làm nhục (shaming/toxic parenting). Khi con phạm lỗi, tuyệt đối không chê trách trước đám đông — kéo con ra chỗ riêng để giữ nhân phẩm và giúp trẻ tự hình thành kỷ luật nội tâm.`,
  `Trao quyền được thử và sai — Đừng vì sợ con vấp ngã mà làm thay mọi việc; giáo dục là quá trình tự hoàn thiện qua tương tác với môi trường (Montessori, Piaget). Như Lão Tử dạy học trò làm gốm: kiên nhẫn đứng nhìn con làm hỏng, rồi hướng dẫn con tự nhận ra nguyên nhân.`,
  `Thiết lập giới hạn từ bi — Trẻ cần quy tắc để cảm thấy an toàn, như dòng sông cần có bờ. Nuôi dạy kiểu Uy quyền (Authoritative): giữ vững kỷ luật nhưng luôn giải thích lý do bằng sự ấm áp, để con hiểu luật lệ là để bảo vệ chứ không phải trừng phạt.`,
  `Dạy lễ nghĩa qua kỹ năng sinh hoạt — Đạo đức không đến từ lý thuyết mà từ "Góc sinh hoạt" (Practical Life trong Montessori) và các phép tắc đời thường trong Đệ Tử Quy: cất đồ đúng chỗ, kính trên nhường dưới, ăn uống từ tốn — hình thành sự ngăn nắp và khả năng tập trung.`,
  `Ghi nhận quá trình thay vì tố chất — Tránh khen kiểu "con là thiên tài" (dễ sinh kiêu ngạo) lẫn chê bai triệt tiêu tự tin. Khen sự nỗ lực cụ thể ("mẹ thấy con rất kiên trì") để trẻ so sánh với chính mình hôm qua thay vì ganh đua với người khác.`,
  `Chuyển hóa tư duy vị kỷ — Trẻ nhỏ có bản năng coi mình là trung tâm (theo Piaget). Dùng tình huống thực tế để khơi gợi sự thấu cảm, kết hợp tinh thần "phiếm ái chúng" (yêu thương rộng khắp) trong Đệ Tử Quy để trẻ học cách chia sẻ tự nguyện thay vì bị ép buộc.`,
  `Đối xử công bằng giữa các con — Thiên vị (differential parenting) gây trầm cảm, tự ti ở trẻ bị "ra rìa" và nuôi tính kiêu ngạo ở trẻ được cưng chiều. Đệ Tử Quy dạy coi trọng tình thân hơn tranh giành vật chất — cha mẹ cần công bằng rõ ràng giữa các con.`,
  `Buông bỏ kiểm soát tuổi dậy thì — Ở tuổi vị thành niên (giai đoạn thao tác hình thức của Piaget), cái tôi của trẻ nhạy cảm với áp đặt. Học cách các bậc đế vương: lùi lại, không dùng "đạo lý hy sinh" để trói buộc, chuyển từ vai trò quản lý sang người cố vấn (mentor).`,
  `Trí tuệ phải song hành cùng đạo đức — Khổng Tử cảnh báo "học mà không suy nghĩ thì u mê, có trí mà không có đức là tai họa". Hướng con theo đuổi "Nghĩa" (giá trị cốt lõi, trách nhiệm) thay vì chạy theo "Danh" (hư vinh, mạng xã hội) — học vấn là phương tiện để làm người tử tế, không phải đích đến.`,
];
